"""
Report Generator.

Generates accessibility testing reports in multiple formats:
1. JSON — machine-readable, schema-validated
2. HTML — human-readable with embedded screenshots, evidence, and remediation
3. CSV — for spreadsheet-based review workflows

Design principles:
- Reports are GENERATED FROM validated Finding objects, not from LLM text.
- Screenshots are embedded as data URIs in HTML reports.
- Every finding links back to its evidence.
- Reports include an explicit disclaimer that they do not constitute
  WCAG conformance determination.

The HTML template uses Jinja2.
"""

from __future__ import annotations

import csv
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from jinja2 import Environment, PackageLoader, select_autoescape, BaseLoader, DictLoader

from accessibility_agent.config import settings
from accessibility_agent.logging_config import get_logger
from accessibility_agent.wcag.schemas import (
    Finding,
    FindingStatus,
    ScanResult,
    WCAGLevel,
)

log = get_logger(__name__)


# ── HTML Template ─────────────────────────────────────────────────────────────

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Accessibility Scan Report — {{ result.url }}</title>
    <style>
        :root {
            --color-confirmed: #d93025;
            --color-likely: #f57c00;
            --color-possible: #f9ab00;
            --color-manual: #1a73e8;
            --color-pass: #1e8e3e;
            --color-na: #5f6368;
        }
        body { font-family: system-ui, sans-serif; max-width: 1200px; margin: 0 auto; padding: 2rem; color: #202124; }
        h1 { font-size: 1.75rem; }
        h2 { font-size: 1.25rem; border-bottom: 2px solid #e8eaed; padding-bottom: 0.5rem; }
        .disclaimer {
            background: #fce8e6; border: 1px solid #ea4335; border-radius: 4px;
            padding: 1rem; margin: 1.5rem 0; font-size: 0.9rem;
        }
        .metrics { display: grid; grid-template-columns: repeat(auto-fit, minmax(160px, 1fr)); gap: 1rem; margin: 1.5rem 0; }
        .metric { background: #f8f9fa; border-radius: 8px; padding: 1rem; text-align: center; }
        .metric .value { font-size: 2rem; font-weight: 700; }
        .metric .label { font-size: 0.8rem; color: #5f6368; }
        .finding { border: 1px solid #e8eaed; border-radius: 8px; margin: 1rem 0; padding: 1.25rem; }
        .finding.confirmed { border-left: 4px solid var(--color-confirmed); }
        .finding.likely { border-left: 4px solid var(--color-likely); }
        .finding.possible { border-left: 4px solid var(--color-possible); }
        .finding.requires_manual_review { border-left: 4px solid var(--color-manual); }
        .finding.pass { border-left: 4px solid var(--color-pass); }
        .badge {
            display: inline-block; padding: 2px 8px; border-radius: 12px;
            font-size: 0.75rem; font-weight: 600; text-transform: uppercase;
        }
        .badge-confirmed { background: #fce8e6; color: var(--color-confirmed); }
        .badge-likely { background: #fef0e6; color: var(--color-likely); }
        .badge-possible { background: #fef8e1; color: var(--color-possible); }
        .badge-manual { background: #e8f0fe; color: var(--color-manual); }
        .badge-pass { background: #e6f4ea; color: var(--color-pass); }
        .badge-A { background: #fce8e6; color: var(--color-confirmed); }
        .badge-AA { background: #fef0e6; color: var(--color-likely); }
        .badge-AAA { background: #f8f9fa; color: #5f6368; }
        .wcag-ref { font-family: monospace; font-size: 0.85rem; }
        pre, code { background: #f8f9fa; border-radius: 4px; padding: 0.2em 0.5em; font-size: 0.85rem; overflow-x: auto; }
        pre { padding: 1rem; }
        details summary { cursor: pointer; color: #1a73e8; margin-top: 0.5rem; }
        .evidence-screenshot img { max-width: 100%; border: 1px solid #e8eaed; border-radius: 4px; margin-top: 0.5rem; }
        .remediation { background: #e6f4ea; border-radius: 6px; padding: 1rem; margin-top: 1rem; }
        .manual-test { background: #e8f0fe; border-radius: 6px; padding: 1rem; margin-top: 1rem; }
        footer { margin-top: 3rem; color: #5f6368; font-size: 0.8rem; border-top: 1px solid #e8eaed; padding-top: 1rem; }
    </style>
</head>
<body>
<h1>♿ Accessibility Scan Report</h1>

<div class="disclaimer">
    <strong>⚠️ Important:</strong> This report was generated by an automated/AI-assisted accessibility testing tool.
    A clean scan result does <strong>not</strong> constitute WCAG conformance.
    Human expert review is always required for complete accessibility conformance determination.
    Screen reader behavior was <strong>not</strong> directly verified in this scan.
</div>

<h2>Scan Details</h2>
<table>
    <tr><th>URL</th><td><a href="{{ result.url }}">{{ result.url }}</a></td></tr>
    <tr><th>Mode</th><td>{{ result.scan_mode }}</td></tr>
    <tr><th>Browser</th><td>{{ result.browser }}</td></tr>
    <tr><th>Viewport</th><td>{{ result.viewport }}</td></tr>
    <tr><th>Started</th><td>{{ result.started_at.strftime('%Y-%m-%d %H:%M:%S UTC') }}</td></tr>
    <tr><th>Completed</th><td>{{ result.completed_at.strftime('%Y-%m-%d %H:%M:%S UTC') if result.completed_at else 'N/A' }}</td></tr>
    <tr><th>Run ID</th><td><code>{{ result.run_id }}</code></td></tr>
    <tr><th>Agent Steps</th><td>{{ result.agent_steps }}</td></tr>
</table>

<h2>Metrics</h2>
<div class="metrics">
    <div class="metric"><div class="value" style="color:var(--color-confirmed)">{{ m.confirmed_findings }}</div><div class="label">Confirmed Findings</div></div>
    <div class="metric"><div class="value" style="color:var(--color-likely)">{{ m.likely_findings }}</div><div class="label">Likely Findings</div></div>
    <div class="metric"><div class="value" style="color:var(--color-manual)">{{ m.manual_review_findings }}</div><div class="label">Manual Review</div></div>
    <div class="metric"><div class="value" style="color:var(--color-pass)">{{ m.passed_checks }}</div><div class="label">Passed Checks</div></div>
    <div class="metric"><div class="value">{{ m.duplicate_findings }}</div><div class="label">Duplicates</div></div>
    <div class="metric"><div class="value">{{ m.level_a_findings }}</div><div class="label">Level A Failures</div></div>
    <div class="metric"><div class="value">{{ m.level_aa_findings }}</div><div class="label">Level AA Failures</div></div>
    <div class="metric"><div class="value">{{ m.automated_findings }}</div><div class="label">Automated</div></div>
    <div class="metric"><div class="value">{{ m.ai_assisted_findings }}</div><div class="label">AI-Assisted</div></div>
</div>

{% if m.wcag_criteria_affected %}
<h2>WCAG Criteria Affected</h2>
<p>{{ m.wcag_criteria_affected | sort | join(', ') }}</p>
{% endif %}

<h2>Findings</h2>
{% set active_findings = findings | selectattr('duplicate_of', 'none') | list %}
{% if not active_findings %}
<p style="color:var(--color-pass)">✅ No unique findings to display.</p>
{% endif %}

{% for finding in active_findings %}
<div class="finding {{ finding.status.value }}">
    <div style="display:flex; gap:0.5rem; align-items:center; flex-wrap:wrap; margin-bottom:0.75rem;">
        <span class="badge badge-{{ finding.status.value }}">{{ finding.status.value | replace('_',' ') }}</span>
        <span class="badge badge-{{ finding.wcag.level.value }}">WCAG {{ finding.wcag.level.value }}</span>
        <span class="wcag-ref">{{ finding.wcag.version }} SC {{ finding.wcag.success_criterion }} — {{ finding.wcag.title }}</span>
        <small style="margin-left:auto; color:#5f6368">{{ finding.finding_id }}</small>
    </div>

    <h3 style="margin:0 0 0.5rem">{{ finding.description }}</h3>

    {% if finding.element.selector %}
    <p><strong>Element:</strong> <code>{{ finding.element.selector }}</code></p>
    {% endif %}
    {% if finding.element.html %}
    <details><summary>Element HTML</summary><pre>{{ finding.element.html | e }}</pre></details>
    {% endif %}
    {% if finding.actual_result %}
    <p><strong>Actual:</strong> {{ finding.actual_result }}</p>
    {% endif %}
    {% if finding.expected_result %}
    <p><strong>Expected:</strong> {{ finding.expected_result }}</p>
    {% endif %}
    {% if finding.root_cause %}
    <p><strong>Root Cause:</strong> {{ finding.root_cause }}</p>
    {% endif %}
    {% if finding.ai_reasoning %}
    <details>
        <summary>AI Reasoning (supplementary, not evidence)</summary>
        <p style="font-style:italic; color:#5f6368">{{ finding.ai_reasoning }}</p>
    </details>
    {% endif %}

    {% if finding.remediation and finding.remediation.summary %}
    <div class="remediation">
        <strong>🔧 Remediation:</strong> {{ finding.remediation.summary }}
        {% if finding.remediation.html_fix %}
        <details><summary>HTML Fix</summary><pre>{{ finding.remediation.html_fix | e }}</pre></details>
        {% endif %}
        {% if finding.remediation.aria_fix %}
        <details><summary>ARIA Fix</summary><pre>{{ finding.remediation.aria_fix | e }}</pre></details>
        {% endif %}
    </div>
    {% endif %}

    {% if finding.manual_test_procedure %}
    <div class="manual-test">
        <strong>📋 Manual Test Required ({{ finding.manual_test_procedure.test_id }}):</strong>
        {{ finding.manual_test_procedure.purpose }}
        <details>
            <summary>Steps</summary>
            <ol>{% for step in finding.manual_test_procedure.steps %}<li>{{ step }}</li>{% endfor %}</ol>
            <p><strong>Expected:</strong> {{ finding.manual_test_procedure.expected_result }}</p>
        </details>
    </div>
    {% endif %}

    {% if finding.evidence %}
    <details>
        <summary>Evidence ({{ finding.evidence | length }})</summary>
        {% for ev in finding.evidence %}
        <div style="margin: 0.5rem 0; padding: 0.5rem; background:#f8f9fa; border-radius:4px;">
            <strong>{{ ev.evidence_type }}</strong> — {{ ev.description }}
            {% if ev.evidence_type == 'screenshot' and ev.data %}
            <div class="evidence-screenshot"><img src="data:image/png;base64,{{ ev.data }}" alt="Screenshot evidence"></div>
            {% elif ev.data and ev.evidence_type != 'screenshot' %}
            <details><summary>View data</summary><pre>{{ ev.data[:2000] | e }}</pre></details>
            {% endif %}
        </div>
        {% endfor %}
    </details>
    {% endif %}

    {% if finding.related_findings %}
    <p style="font-size:0.8rem; color:#5f6368">Related ({{ finding.related_findings | length }} duplicates): {{ finding.related_findings | join(', ') }}</p>
    {% endif %}
</div>
{% endfor %}

{% if result.errors %}
<h2>Scan Errors</h2>
{% for err in result.errors %}
<p style="color:var(--color-confirmed)">⚠️ {{ err }}</p>
{% endfor %}
{% endif %}

<footer>
    <p>Generated by <strong>AI Accessibility Testing Agent v{{ version }}</strong> at {{ generated_at }} UTC.</p>
    <p>
        This tool assists accessibility testing but <strong>does not replace</strong> expert human review.
        Automated tools typically detect 30–40% of real accessibility issues.
    </p>
</footer>
</body>
</html>"""


class ReportGenerator:
    """
    Generates scan reports in JSON, HTML, and CSV formats.

    Input: A validated ScanResult object.
    Output: Report files written to the configured report directory.
    """

    def __init__(self, output_dir: Path | None = None) -> None:
        self._output_dir = output_dir or settings.report_dir
        self._output_dir.mkdir(parents=True, exist_ok=True)
        self._env = Environment(
            loader=DictLoader({"report.html": HTML_TEMPLATE}),
            autoescape=select_autoescape(["html"]),
        )

    def generate(self, result: ScanResult) -> dict[str, Path]:
        """
        Generate all configured report formats.

        Returns a dict mapping format name to output file path.
        """
        result.finalize()
        paths: dict[str, Path] = {}

        formats = settings.report_formats

        if "json" in formats:
            paths["json"] = self._write_json(result)
        if "html" in formats:
            paths["html"] = self._write_html(result)
        if "csv" in formats:
            paths["csv"] = self._write_csv(result)

        log.info("report.generated", run_id=result.run_id, paths={k: str(v) for k, v in paths.items()})
        return paths

    def _write_json(self, result: ScanResult) -> Path:
        """Write machine-readable JSON report."""
        path = self._output_dir / f"{result.run_id}_report.json"
        data = result.model_dump(mode="json")
        path.write_text(json.dumps(data, indent=2, default=str), encoding="utf-8")
        log.info("report.json_written", path=str(path))
        return path

    def _write_html(self, result: ScanResult) -> Path:
        """Write human-readable HTML report."""
        path = self._output_dir / f"{result.run_id}_report.html"

        template = self._env.get_template("report.html")
        html = template.render(
            result=result,
            findings=result.findings,
            m=result.metrics,
            version="0.1.0",
            generated_at=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S"),
        )
        path.write_text(html, encoding="utf-8")
        log.info("report.html_written", path=str(path))
        return path

    def _write_csv(self, result: ScanResult) -> Path:
        """Write CSV report for spreadsheet-based review workflows."""
        path = self._output_dir / f"{result.run_id}_findings.csv"

        columns = [
            "finding_id", "status", "wcag_version", "wcag_sc", "wcag_title",
            "wcag_level", "detection_method", "confidence", "url", "selector",
            "description", "actual_result", "expected_result", "root_cause",
            "manual_review_required", "duplicate_of",
        ]

        with path.open("w", newline="", encoding="utf-8") as f:
            writer = csv.DictWriter(f, fieldnames=columns)
            writer.writeheader()
            for finding in result.findings:
                writer.writerow({
                    "finding_id": finding.finding_id,
                    "status": finding.status.value,
                    "wcag_version": finding.wcag.version.value,
                    "wcag_sc": finding.wcag.success_criterion,
                    "wcag_title": finding.wcag.title,
                    "wcag_level": finding.wcag.level.value,
                    "detection_method": finding.detection_method.value,
                    "confidence": finding.confidence,
                    "url": finding.url,
                    "selector": finding.element.selector,
                    "description": finding.description,
                    "actual_result": finding.actual_result,
                    "expected_result": finding.expected_result,
                    "root_cause": finding.root_cause,
                    "manual_review_required": finding.manual_review_required,
                    "duplicate_of": finding.duplicate_of or "",
                })

        log.info("report.csv_written", path=str(path), rows=len(result.findings))
        return path
