"""
WCAG 2.2 Knowledge Base — Complete Reference Data

All 78 WCAG 2.2 Success Criteria with:
- Official title, level, principle, W3C URL
- Plain-English description
- Keywords for semantic search (used by RAG engine)
- Common failure patterns
- Mapped axe-core rule IDs
- Related ARIA patterns

Source: https://www.w3.org/TR/WCAG22/ (W3C Recommendation, October 2023)

This is the authoritative ground truth used by:
1. RAGEngine for finding-to-criterion retrieval
2. ReasoningEngine for prompt enrichment with verified citations
3. ContradictionDetector for validating AI-generated fixes
"""

from __future__ import annotations

# ── WCAG 2.2 Success Criteria ────────────────────────────────────────────────
# Each entry: sc_number → {title, level, principle, url, description, keywords,
#                          common_failures, axe_rules, aria_patterns}

WCAG_22: dict[str, dict] = {

    # ═══════════════════════════════════════════════════════════════════
    # PRINCIPLE 1: PERCEIVABLE
    # ═══════════════════════════════════════════════════════════════════

    # Guideline 1.1 — Text Alternatives
    "1.1.1": {
        "title": "Non-text Content",
        "level": "A",
        "principle": "Perceivable",
        "url": "https://www.w3.org/TR/WCAG22/#non-text-content",
        "description": (
            "All non-text content presented to the user has a text alternative that serves "
            "the equivalent purpose, except for decorative, formatting, invisible, or CAPTCHA content."
        ),
        "keywords": ["alt", "alt text", "image", "icon", "photo", "svg", "canvas", "aria-label",
                     "aria-labelledby", "title", "non-text", "decorative", "informative", "functional"],
        "common_failures": [
            "img element missing alt attribute",
            "img with empty alt but is informative (conveys meaning)",
            "img with alt text that is filename or placeholder (e.g. 'image123.jpg')",
            "icon button with no accessible name",
            "SVG with no title or aria-label",
            "Canvas element with no fallback text",
            "Input type=image missing alt attribute",
        ],
        "axe_rules": ["image-alt", "input-image-alt", "object-alt", "area-alt", "role-img-alt",
                      "svg-img-alt", "image-redundant-alt"],
        "aria_patterns": ["img role", "presentation role for decorative images"],
        "fix_hint": "Add alt='descriptive text' to informative images. Use alt='' for decorative images.",
    },

    # Guideline 1.2 — Time-based Media
    "1.2.1": {
        "title": "Audio-only and Video-only (Prerecorded)",
        "level": "A",
        "principle": "Perceivable",
        "url": "https://www.w3.org/TR/WCAG22/#audio-only-and-video-only-prerecorded",
        "description": "Prerecorded audio-only and video-only content has a text alternative or audio description.",
        "keywords": ["audio", "video", "transcript", "captions", "prerecorded", "media", "podcast"],
        "common_failures": ["audio without transcript", "video without text alternative"],
        "axe_rules": [],
        "aria_patterns": [],
        "fix_hint": "Provide a text transcript for audio. Provide a text description for silent video.",
    },
    "1.2.2": {
        "title": "Captions (Prerecorded)",
        "level": "A",
        "principle": "Perceivable",
        "url": "https://www.w3.org/TR/WCAG22/#captions-prerecorded",
        "description": "Captions are provided for all prerecorded audio content in synchronized media.",
        "keywords": ["captions", "subtitles", "video", "audio track", "synchronized media", "deaf"],
        "common_failures": ["video element has no track element with kind=captions", "auto-generated captions not verified"],
        "axe_rules": [],
        "aria_patterns": [],
        "fix_hint": "Add <track kind='captions' src='captions.vtt'> inside <video> elements.",
    },
    "1.2.3": {
        "title": "Audio Description or Media Alternative (Prerecorded)",
        "level": "A",
        "principle": "Perceivable",
        "url": "https://www.w3.org/TR/WCAG22/#audio-description-or-media-alternative-prerecorded",
        "description": "An audio description or text alternative is provided for synchronized video.",
        "keywords": ["audio description", "video description", "visual information", "blind", "media"],
        "common_failures": ["important visual-only information in video has no audio description"],
        "axe_rules": [],
        "aria_patterns": [],
        "fix_hint": "Add audio description track or provide full text transcript with visual descriptions.",
    },
    "1.2.4": {
        "title": "Captions (Live)",
        "level": "AA",
        "principle": "Perceivable",
        "url": "https://www.w3.org/TR/WCAG22/#captions-live",
        "description": "Captions are provided for all live audio content in synchronized media.",
        "keywords": ["live captions", "live video", "live stream", "real-time captions"],
        "common_failures": ["live webinar or stream has no real-time captioning"],
        "axe_rules": [],
        "aria_patterns": [],
        "fix_hint": "Provide CART (Communication Access Realtime Translation) for live events.",
    },
    "1.2.5": {
        "title": "Audio Description (Prerecorded)",
        "level": "AA",
        "principle": "Perceivable",
        "url": "https://www.w3.org/TR/WCAG22/#audio-description-prerecorded",
        "description": "Audio description is provided for all prerecorded video content.",
        "keywords": ["audio description", "video", "visual content", "screen reader", "blind"],
        "common_failures": ["prerecorded video lacks audio description of visual content"],
        "axe_rules": [],
        "aria_patterns": [],
        "fix_hint": "Record an audio description track describing all important visual information.",
    },

    # Guideline 1.3 — Adaptable
    "1.3.1": {
        "title": "Info and Relationships",
        "level": "A",
        "principle": "Perceivable",
        "url": "https://www.w3.org/TR/WCAG22/#info-and-relationships",
        "description": (
            "Information, structure, and relationships conveyed through presentation can be "
            "programmatically determined or are available in text."
        ),
        "keywords": ["table", "header", "heading", "list", "form", "label", "fieldset", "legend",
                     "th", "td", "scope", "aria-required", "semantic", "structure", "role", "landmark"],
        "common_failures": [
            "table used for layout without role=presentation",
            "table with no th elements or scope attributes",
            "heading hierarchy skipped (h1 → h3 missing h2)",
            "form input has no associated label",
            "required field indicated only by color (no aria-required or asterisk text)",
            "list items not inside ul or ol",
            "fieldset missing legend",
        ],
        "axe_rules": ["label", "td-headers-attr", "th-has-data-cells", "scope-attr-valid",
                      "table-duplicate-name", "table-fake-caption", "empty-heading",
                      "list", "listitem", "definition-list", "dlitem"],
        "aria_patterns": ["landmark roles", "table pattern", "form pattern"],
        "fix_hint": "Use semantic HTML. Associate form labels with inputs using for/id or aria-labelledby.",
    },
    "1.3.2": {
        "title": "Meaningful Sequence",
        "level": "A",
        "principle": "Perceivable",
        "url": "https://www.w3.org/TR/WCAG22/#meaningful-sequence",
        "description": "Content reading sequence is meaningful and can be programmatically determined.",
        "keywords": ["reading order", "dom order", "sequence", "css positioning", "float", "grid", "flexbox"],
        "common_failures": ["DOM order does not match visual order due to CSS positioning"],
        "axe_rules": [],
        "aria_patterns": [],
        "fix_hint": "Ensure DOM order matches the logical reading order. Do not use CSS to reorder content.",
    },
    "1.3.3": {
        "title": "Sensory Characteristics",
        "level": "A",
        "principle": "Perceivable",
        "url": "https://www.w3.org/TR/WCAG22/#sensory-characteristics",
        "description": "Instructions don't rely solely on shape, color, size, visual location, orientation, or sound.",
        "keywords": ["shape", "color", "location", "orientation", "sound", "instructions", "sensory"],
        "common_failures": ["'Click the red button'", "'See the form on the right'"],
        "axe_rules": [],
        "aria_patterns": [],
        "fix_hint": "Supplement visual/spatial references with text labels (e.g., 'Click the Submit button').",
    },
    "1.3.4": {
        "title": "Orientation",
        "level": "AA",
        "principle": "Perceivable",
        "url": "https://www.w3.org/TR/WCAG22/#orientation",
        "description": "Content does not restrict its view and operation to a single display orientation.",
        "keywords": ["orientation", "portrait", "landscape", "rotation", "mobile", "responsive"],
        "common_failures": ["CSS locks orientation to portrait or landscape only"],
        "axe_rules": [],
        "aria_patterns": [],
        "fix_hint": "Remove CSS that locks screen orientation unless essential (e.g., a piano app).",
    },
    "1.3.5": {
        "title": "Identify Input Purpose",
        "level": "AA",
        "principle": "Perceivable",
        "url": "https://www.w3.org/TR/WCAG22/#identify-input-purpose",
        "description": "The purpose of each form input collecting personal information can be programmatically determined.",
        "keywords": ["autocomplete", "name", "email", "phone", "address", "input purpose", "personal data"],
        "common_failures": ["input collecting name/email/phone missing autocomplete attribute"],
        "axe_rules": ["autocomplete-valid"],
        "aria_patterns": [],
        "fix_hint": "Add autocomplete='name', autocomplete='email' etc. to personal data inputs.",
    },

    # Guideline 1.4 — Distinguishable
    "1.4.1": {
        "title": "Use of Color",
        "level": "A",
        "principle": "Perceivable",
        "url": "https://www.w3.org/TR/WCAG22/#use-of-color",
        "description": "Color is not used as the only visual means of conveying information.",
        "keywords": ["color", "red", "green", "error", "success", "link", "colorblind", "distinguishable"],
        "common_failures": [
            "error state indicated only by red border (no text error message)",
            "required fields marked only by color",
            "links indistinguishable from body text except by color",
        ],
        "axe_rules": ["link-in-text-block"],
        "aria_patterns": [],
        "fix_hint": "Always pair color with a secondary indicator (icon, text label, pattern, underline).",
    },
    "1.4.2": {
        "title": "Audio Control",
        "level": "A",
        "principle": "Perceivable",
        "url": "https://www.w3.org/TR/WCAG22/#audio-control",
        "description": "Audio that plays automatically for more than 3 seconds must be pausable or stoppable.",
        "keywords": ["audio", "autoplay", "background sound", "music", "pause", "stop", "volume"],
        "common_failures": ["audio or video autoplays with sound and no controls"],
        "axe_rules": [],
        "aria_patterns": [],
        "fix_hint": "Add controls attribute to <audio> and <video>. Avoid autoplay with sound.",
    },
    "1.4.3": {
        "title": "Contrast (Minimum)",
        "level": "AA",
        "principle": "Perceivable",
        "url": "https://www.w3.org/TR/WCAG22/#contrast-minimum",
        "description": "Text has a contrast ratio of at least 4.5:1 (3:1 for large text).",
        "keywords": ["contrast", "color ratio", "text", "background", "foreground", "readability",
                     "low contrast", "gray", "light", "WCAG contrast"],
        "common_failures": [
            "light gray text on white background",
            "white text on light background",
            "placeholder text with insufficient contrast",
            "disabled element text still needs to be distinguishable",
        ],
        "axe_rules": ["color-contrast", "color-contrast-enhanced"],
        "aria_patterns": [],
        "fix_hint": "Use a contrast checker. Body text needs 4.5:1 ratio. Large text (18pt+) needs 3:1.",
    },
    "1.4.4": {
        "title": "Resize Text",
        "level": "AA",
        "principle": "Perceivable",
        "url": "https://www.w3.org/TR/WCAG22/#resize-text",
        "description": "Text can be resized up to 200% without loss of content or functionality.",
        "keywords": ["zoom", "resize", "text size", "font size", "rem", "em", "px", "viewport"],
        "common_failures": ["fixed px font sizes prevent browser zoom", "content overflows when zoomed"],
        "axe_rules": ["meta-viewport"],
        "aria_patterns": [],
        "fix_hint": "Use rem or em units for font sizes. Test at 200% browser zoom.",
    },
    "1.4.5": {
        "title": "Images of Text",
        "level": "AA",
        "principle": "Perceivable",
        "url": "https://www.w3.org/TR/WCAG22/#images-of-text",
        "description": "Text is not presented as images except for logos and decorative text.",
        "keywords": ["image of text", "text in image", "logo", "banner", "CSS text vs image"],
        "common_failures": ["navigation or heading text rendered as image instead of CSS-styled HTML text"],
        "axe_rules": [],
        "aria_patterns": [],
        "fix_hint": "Replace text images with real HTML text styled with CSS.",
    },
    "1.4.10": {
        "title": "Reflow",
        "level": "AA",
        "principle": "Perceivable",
        "url": "https://www.w3.org/TR/WCAG22/#reflow",
        "description": "Content can reflow in a single column at 320 CSS pixels width without horizontal scrolling.",
        "keywords": ["reflow", "320px", "mobile", "horizontal scroll", "responsive", "overflow"],
        "common_failures": ["content requires horizontal scrolling at 320px width", "fixed-width layouts"],
        "axe_rules": [],
        "aria_patterns": [],
        "fix_hint": "Test at 400% zoom (equivalent to 320px). Use responsive design with max-width and flex/grid.",
    },
    "1.4.11": {
        "title": "Non-text Contrast",
        "level": "AA",
        "principle": "Perceivable",
        "url": "https://www.w3.org/TR/WCAG22/#non-text-contrast",
        "description": "UI components and graphical objects have a contrast ratio of at least 3:1.",
        "keywords": ["focus indicator", "border", "input border", "icon contrast", "button border",
                     "graph", "chart", "UI component", "non-text contrast"],
        "common_failures": [
            "input field border has contrast less than 3:1 against background",
            "focus indicator is too thin or low contrast",
            "icon has less than 3:1 contrast",
        ],
        "axe_rules": [],
        "aria_patterns": [],
        "fix_hint": "Ensure form inputs, focus rings, and icons have at least 3:1 contrast ratio.",
    },
    "1.4.12": {
        "title": "Text Spacing",
        "level": "AA",
        "principle": "Perceivable",
        "url": "https://www.w3.org/TR/WCAG22/#text-spacing",
        "description": "No loss of content when overriding line height, letter spacing, word spacing, and paragraph spacing.",
        "keywords": ["text spacing", "line height", "letter spacing", "word spacing", "truncation", "overflow"],
        "common_failures": ["text truncates when letter-spacing is increased", "fixed-height containers clip text"],
        "axe_rules": [],
        "aria_patterns": [],
        "fix_hint": "Use min-height instead of height for text containers. Test with the WCAG text spacing bookmarklet.",
    },
    "1.4.13": {
        "title": "Content on Hover or Focus",
        "level": "AA",
        "principle": "Perceivable",
        "url": "https://www.w3.org/TR/WCAG22/#content-on-hover-or-focus",
        "description": "Tooltip/popover content that appears on hover/focus is dismissible, hoverable, and persistent.",
        "keywords": ["tooltip", "hover", "focus", "popover", "dismissible", "persistent"],
        "common_failures": [
            "tooltip disappears before user can read it",
            "tooltip cannot be dismissed without moving pointer",
            "tooltip blocks other content",
        ],
        "axe_rules": [],
        "aria_patterns": ["tooltip pattern"],
        "fix_hint": "Use role=tooltip. Ensure tooltips stay visible when hovering over them. Allow Escape to dismiss.",
    },

    # ═══════════════════════════════════════════════════════════════════
    # PRINCIPLE 2: OPERABLE
    # ═══════════════════════════════════════════════════════════════════

    # Guideline 2.1 — Keyboard Accessible
    "2.1.1": {
        "title": "Keyboard",
        "level": "A",
        "principle": "Operable",
        "url": "https://www.w3.org/TR/WCAG22/#keyboard",
        "description": "All functionality is operable through a keyboard interface without requiring specific timings.",
        "keywords": ["keyboard", "tab", "enter", "space", "arrow key", "mouse-only", "keyboard accessible",
                     "onclick", "onmouseover", "drag", "gestures"],
        "common_failures": [
            "click handler only (no keyboard equivalent)",
            "custom widget with no keyboard interaction",
            "drag-and-drop with no keyboard alternative",
            "onclick on a div/span instead of button",
        ],
        "axe_rules": ["keyboard-scrollable-region-focusable"],
        "aria_patterns": ["button pattern", "slider pattern", "tree pattern"],
        "fix_hint": "Use <button> or <a> instead of div/span for interactive elements. Add keyboard event handlers.",
    },
    "2.1.2": {
        "title": "No Keyboard Trap",
        "level": "A",
        "principle": "Operable",
        "url": "https://www.w3.org/TR/WCAG22/#no-keyboard-trap",
        "description": "Keyboard focus can be moved to and away from a component using only the keyboard.",
        "keywords": ["keyboard trap", "focus trap", "modal", "dialog", "escape", "tab", "stuck", "imprisoned"],
        "common_failures": [
            "focus trapped inside modal that doesn't close on Escape",
            "focus escapes dialog and lands on background page",
            "iframe captures all keyboard input",
        ],
        "axe_rules": ["frame-focusable-content"],
        "aria_patterns": ["dialog pattern", "alertdialog pattern"],
        "fix_hint": "Implement focus management in modals. Trap focus inside dialogs. Allow Escape to close.",
    },
    "2.1.3": {
        "title": "Keyboard (No Exception)",
        "level": "AAA",
        "principle": "Operable",
        "url": "https://www.w3.org/TR/WCAG22/#keyboard-no-exception",
        "description": "All functionality is operable through a keyboard with no exceptions.",
        "keywords": ["keyboard", "AAA", "no exception"],
        "common_failures": ["any functionality requiring mouse"],
        "axe_rules": [],
        "aria_patterns": [],
        "fix_hint": "All functionality including freehand drawing must have a keyboard alternative.",
    },
    "2.1.4": {
        "title": "Character Key Shortcuts",
        "level": "A",
        "principle": "Operable",
        "url": "https://www.w3.org/TR/WCAG22/#character-key-shortcuts",
        "description": "Single-character key shortcuts can be turned off or remapped.",
        "keywords": ["shortcut", "hotkey", "single key", "keyboard shortcut", "remap"],
        "common_failures": ["app uses single-letter shortcuts that conflict with screen reader commands"],
        "axe_rules": [],
        "aria_patterns": [],
        "fix_hint": "Allow users to turn off or remap single-character shortcuts in settings.",
    },

    # Guideline 2.2 — Enough Time
    "2.2.1": {
        "title": "Timing Adjustable",
        "level": "A",
        "principle": "Operable",
        "url": "https://www.w3.org/TR/WCAG22/#timing-adjustable",
        "description": "Time limits can be turned off, adjusted, or extended by the user.",
        "keywords": ["timeout", "session", "time limit", "extend", "adjust", "expiry"],
        "common_failures": ["session timeout without warning or extension option"],
        "axe_rules": [],
        "aria_patterns": [],
        "fix_hint": "Warn users before session expires and offer to extend. Allow 20 seconds minimum to respond.",
    },
    "2.2.2": {
        "title": "Pause, Stop, Hide",
        "level": "A",
        "principle": "Operable",
        "url": "https://www.w3.org/TR/WCAG22/#pause-stop-hide",
        "description": "Moving, blinking, scrolling, or auto-updating content can be paused, stopped, or hidden.",
        "keywords": ["animation", "carousel", "auto-play", "blinking", "scrolling", "ticker", "pause", "stop"],
        "common_failures": [
            "carousel with no pause button",
            "animated banner with no stop control",
            "news ticker that cannot be stopped",
        ],
        "axe_rules": ["blink"],
        "aria_patterns": [],
        "fix_hint": "Add pause/stop controls to carousels and animations. Respect prefers-reduced-motion.",
    },

    # Guideline 2.3 — Seizures
    "2.3.1": {
        "title": "Three Flashes or Below Threshold",
        "level": "A",
        "principle": "Operable",
        "url": "https://www.w3.org/TR/WCAG22/#three-flashes-or-below-threshold",
        "description": "Content does not flash more than three times per second.",
        "keywords": ["flash", "strobe", "seizure", "photosensitive", "epilepsy", "blink"],
        "common_failures": ["flashing animation faster than 3Hz"],
        "axe_rules": [],
        "aria_patterns": [],
        "fix_hint": "Avoid flashing content. If necessary, flash less than 3 times per second.",
    },

    # Guideline 2.4 — Navigable
    "2.4.1": {
        "title": "Bypass Blocks",
        "level": "A",
        "principle": "Operable",
        "url": "https://www.w3.org/TR/WCAG22/#bypass-blocks",
        "description": "A mechanism to bypass repeated content blocks exists (skip links, landmarks).",
        "keywords": ["skip link", "skip navigation", "bypass", "landmark", "main", "header", "nav"],
        "common_failures": [
            "no skip to main content link",
            "page has no landmark roles (main, nav, header)",
        ],
        "axe_rules": ["bypass", "landmark-one-main", "region"],
        "aria_patterns": ["landmark pattern"],
        "fix_hint": "Add <a href='#main'>Skip to main content</a> as the first element. Use landmark elements.",
    },
    "2.4.2": {
        "title": "Page Titled",
        "level": "A",
        "principle": "Operable",
        "url": "https://www.w3.org/TR/WCAG22/#page-titled",
        "description": "Web pages have titles that describe their topic or purpose.",
        "keywords": ["title", "page title", "document title", "tab title"],
        "common_failures": ["<title> is empty", "<title> is the same on every page", "no <title> element"],
        "axe_rules": ["document-title"],
        "aria_patterns": [],
        "fix_hint": "Add a unique, descriptive <title> to every page: <title>Page Name – Site Name</title>",
    },
    "2.4.3": {
        "title": "Focus Order",
        "level": "A",
        "principle": "Operable",
        "url": "https://www.w3.org/TR/WCAG22/#focus-order",
        "description": "Focusable components receive focus in an order that preserves meaning and operability.",
        "keywords": ["focus order", "tab order", "tabindex", "logical order", "reading order", "sequence"],
        "common_failures": [
            "positive tabindex values create unexpected tab order",
            "injected modal focuses wrong element first",
            "focus jumps to unexpected location after action",
        ],
        "axe_rules": ["tabindex"],
        "aria_patterns": [],
        "fix_hint": "Avoid positive tabindex values. Manage focus programmatically when content changes.",
    },
    "2.4.4": {
        "title": "Link Purpose (In Context)",
        "level": "A",
        "principle": "Operable",
        "url": "https://www.w3.org/TR/WCAG22/#link-purpose-in-context",
        "description": "The purpose of each link can be determined from the link text or its context.",
        "keywords": ["link text", "read more", "click here", "learn more", "here", "link purpose", "ambiguous"],
        "common_failures": [
            "link text is 'read more', 'click here', or 'here'",
            "multiple links with same text going to different URLs",
            "image link with no alt text",
        ],
        "axe_rules": ["link-name", "identical-links-same-purpose"],
        "aria_patterns": [],
        "fix_hint": "Use descriptive link text. Add aria-label or aria-labelledby for more context.",
    },
    "2.4.5": {
        "title": "Multiple Ways",
        "level": "AA",
        "principle": "Operable",
        "url": "https://www.w3.org/TR/WCAG22/#multiple-ways",
        "description": "More than one way exists to locate a page within a set of pages.",
        "keywords": ["search", "sitemap", "navigation", "multiple ways", "table of contents"],
        "common_failures": ["website has only one navigation method"],
        "axe_rules": [],
        "aria_patterns": [],
        "fix_hint": "Provide at least two of: site search, sitemap, navigation menu, table of contents.",
    },
    "2.4.6": {
        "title": "Headings and Labels",
        "level": "AA",
        "principle": "Operable",
        "url": "https://www.w3.org/TR/WCAG22/#headings-and-labels",
        "description": "Headings and labels describe the topic or purpose they relate to.",
        "keywords": ["heading", "label", "descriptive", "h1", "h2", "h3", "input label"],
        "common_failures": ["headings that don't describe the content", "labels like 'Field 1'"],
        "axe_rules": [],
        "aria_patterns": [],
        "fix_hint": "Use descriptive headings and labels. Headings should summarize the content that follows.",
    },
    "2.4.7": {
        "title": "Focus Visible",
        "level": "AA",
        "principle": "Operable",
        "url": "https://www.w3.org/TR/WCAG22/#focus-visible",
        "description": "Any keyboard operable user interface has a visible keyboard focus indicator.",
        "keywords": ["focus indicator", "focus visible", "outline", "ring", "border", "keyboard focus",
                     "outline:none", "focus:none", "tab focus"],
        "common_failures": [
            "CSS removes default focus outline: outline: none / outline: 0",
            "custom focus style has insufficient contrast",
            "focus indicator only visible via color change",
        ],
        "axe_rules": ["focus-visible"],
        "aria_patterns": [],
        "fix_hint": "Never set outline:none without a replacement. Use a 2px+ solid outline with 3:1 contrast.",
    },
    "2.4.11": {
        "title": "Focus Not Obscured (Minimum)",
        "level": "AA",
        "principle": "Operable",
        "url": "https://www.w3.org/TR/WCAG22/#focus-not-obscured-minimum",
        "description": "When a component receives keyboard focus, it is not entirely hidden by author-created content.",
        "keywords": ["sticky header", "fixed header", "focus obscured", "hidden focus", "cookie banner"],
        "common_failures": ["sticky header covers focused element", "cookie consent banner hides focused content"],
        "axe_rules": ["scrollable-region-focusable"],
        "aria_patterns": [],
        "fix_hint": "Use scroll-margin-top to account for sticky headers. Ensure focused elements are visible.",
    },
    "2.4.12": {
        "title": "Focus Not Obscured (Enhanced)",
        "level": "AAA",
        "principle": "Operable",
        "url": "https://www.w3.org/TR/WCAG22/#focus-not-obscured-enhanced",
        "description": "When a component receives keyboard focus, no part of the component is hidden by author-created content.",
        "keywords": ["focus obscured", "sticky header", "AAA"],
        "common_failures": ["focused element partially covered by sticky UI"],
        "axe_rules": [],
        "aria_patterns": [],
        "fix_hint": "Ensure no part of a focused element is obscured by other content.",
    },
    "2.4.13": {
        "title": "Focus Appearance",
        "level": "AAA",
        "principle": "Operable",
        "url": "https://www.w3.org/TR/WCAG22/#focus-appearance",
        "description": "The keyboard focus indicator has sufficient size and contrast.",
        "keywords": ["focus indicator", "focus size", "focus contrast", "AAA", "2px", "area"],
        "common_failures": ["focus indicator is too thin", "focus indicator has insufficient contrast"],
        "axe_rules": [],
        "aria_patterns": [],
        "fix_hint": "Focus indicator must be at least 2 CSS pixels and have 3:1 contrast against adjacent colors.",
    },

    # Guideline 2.5 — Input Modalities
    "2.5.1": {
        "title": "Pointer Gestures",
        "level": "A",
        "principle": "Operable",
        "url": "https://www.w3.org/TR/WCAG22/#pointer-gestures",
        "description": "Multi-point and path-based gestures have single-pointer alternatives.",
        "keywords": ["gesture", "swipe", "pinch", "zoom", "rotate", "touch", "multi-touch", "path"],
        "common_failures": ["map requires pinch-to-zoom with no zoom buttons", "carousel requires swipe only"],
        "axe_rules": [],
        "aria_patterns": [],
        "fix_hint": "Provide + / - zoom buttons for maps. Provide prev/next buttons for carousels.",
    },
    "2.5.2": {
        "title": "Pointer Cancellation",
        "level": "A",
        "principle": "Operable",
        "url": "https://www.w3.org/TR/WCAG22/#pointer-cancellation",
        "description": "Functions triggered by single-pointer can be cancelled or undone.",
        "keywords": ["cancel", "undo", "mousedown", "onclick", "accidental click", "pointer"],
        "common_failures": ["action fires on mousedown instead of mouseup", "no undo for accidental clicks"],
        "axe_rules": [],
        "aria_patterns": [],
        "fix_hint": "Fire actions on mouseup/pointerup, not mousedown. Allow abort by moving pointer away.",
    },
    "2.5.3": {
        "title": "Label in Name",
        "level": "A",
        "principle": "Operable",
        "url": "https://www.w3.org/TR/WCAG22/#label-in-name",
        "description": "The accessible name of a component contains the visible text label.",
        "keywords": ["label in name", "accessible name", "aria-label", "visible label", "voice control",
                     "dragon naturally speaking"],
        "common_failures": [
            "aria-label completely replaces visible text (e.g., visible: 'Next', aria-label: 'Navigate to next page')",
            "aria-label does not contain the visible button text",
        ],
        "axe_rules": ["label-content-name-mismatch"],
        "aria_patterns": [],
        "fix_hint": "Ensure aria-label CONTAINS the visible text. Example: aria-label='Next page' for button 'Next'.",
    },
    "2.5.4": {
        "title": "Motion Actuation",
        "level": "A",
        "principle": "Operable",
        "url": "https://www.w3.org/TR/WCAG22/#motion-actuation",
        "description": "Functions triggered by device motion have alternatives and can be disabled.",
        "keywords": ["motion", "shake", "tilt", "gyroscope", "accelerometer", "device motion"],
        "common_failures": ["shake to undo with no alternative", "tilt to scroll with no button alternative"],
        "axe_rules": [],
        "aria_patterns": [],
        "fix_hint": "Provide UI controls as alternatives to motion. Allow disabling motion actuation.",
    },
    "2.5.7": {
        "title": "Dragging Movements",
        "level": "AA",
        "principle": "Operable",
        "url": "https://www.w3.org/TR/WCAG22/#dragging-movements",
        "description": "Dragging operations have a single-pointer alternative.",
        "keywords": ["drag", "drop", "drag and drop", "slider", "reorder"],
        "common_failures": ["drag-and-drop reordering with no keyboard/button alternative"],
        "axe_rules": [],
        "aria_patterns": [],
        "fix_hint": "Add up/down arrow buttons as alternatives to drag-and-drop reordering.",
    },
    "2.5.8": {
        "title": "Target Size (Minimum)",
        "level": "AA",
        "principle": "Operable",
        "url": "https://www.w3.org/TR/WCAG22/#target-size-minimum",
        "description": "Target size for pointer inputs is at least 24x24 CSS pixels.",
        "keywords": ["target size", "touch target", "click target", "button size", "24px", "44px", "small button"],
        "common_failures": ["icon buttons smaller than 24x24px", "close buttons too small"],
        "axe_rules": ["target-size"],
        "aria_patterns": [],
        "fix_hint": "Set minimum width and height of 24px for interactive elements. 44x44px is ideal for touch.",
    },

    # ═══════════════════════════════════════════════════════════════════
    # PRINCIPLE 3: UNDERSTANDABLE
    # ═══════════════════════════════════════════════════════════════════

    # Guideline 3.1 — Readable
    "3.1.1": {
        "title": "Language of Page",
        "level": "A",
        "principle": "Understandable",
        "url": "https://www.w3.org/TR/WCAG22/#language-of-page",
        "description": "The human language of each web page can be programmatically determined.",
        "keywords": ["lang", "language", "html lang", "screen reader", "pronunciation"],
        "common_failures": ["<html> element missing lang attribute", "lang attribute has wrong value"],
        "axe_rules": ["html-has-lang", "html-lang-valid"],
        "aria_patterns": [],
        "fix_hint": "Add lang='en' (or appropriate language code) to the <html> element.",
    },
    "3.1.2": {
        "title": "Language of Parts",
        "level": "AA",
        "principle": "Understandable",
        "url": "https://www.w3.org/TR/WCAG22/#language-of-parts",
        "description": "The human language of each passage or phrase can be programmatically determined.",
        "keywords": ["lang", "language", "multilingual", "foreign phrase", "inline language"],
        "common_failures": ["foreign language quotes without lang attribute on the element"],
        "axe_rules": ["valid-lang"],
        "aria_patterns": [],
        "fix_hint": "Add lang attribute to elements containing text in a different language: <span lang='fr'>",
    },

    # Guideline 3.2 — Predictable
    "3.2.1": {
        "title": "On Focus",
        "level": "A",
        "principle": "Understandable",
        "url": "https://www.w3.org/TR/WCAG22/#on-focus",
        "description": "Receiving focus does not initiate a change of context.",
        "keywords": ["focus", "context change", "navigation", "redirect", "popup", "auto-submit"],
        "common_failures": ["focus on select element automatically submits form or navigates"],
        "axe_rules": [],
        "aria_patterns": [],
        "fix_hint": "Never trigger navigation or form submission on focus alone. Require explicit user action.",
    },
    "3.2.2": {
        "title": "On Input",
        "level": "A",
        "principle": "Understandable",
        "url": "https://www.w3.org/TR/WCAG22/#on-input",
        "description": "Changing settings does not automatically cause a change of context unless warned.",
        "keywords": ["input", "change", "context", "auto-submit", "onchange", "select"],
        "common_failures": ["changing a radio button or select automatically navigates the page"],
        "axe_rules": [],
        "aria_patterns": [],
        "fix_hint": "Require a submit button for form submissions. Warn users if input will change context.",
    },
    "3.2.3": {
        "title": "Consistent Navigation",
        "level": "AA",
        "principle": "Understandable",
        "url": "https://www.w3.org/TR/WCAG22/#consistent-navigation",
        "description": "Navigation mechanisms that repeat across pages appear in the same relative order.",
        "keywords": ["navigation", "consistent", "menu", "order", "repeated"],
        "common_failures": ["navigation order changes between pages"],
        "axe_rules": [],
        "aria_patterns": [],
        "fix_hint": "Keep navigation links in the same order on all pages.",
    },
    "3.2.4": {
        "title": "Consistent Identification",
        "level": "AA",
        "principle": "Understandable",
        "url": "https://www.w3.org/TR/WCAG22/#consistent-identification",
        "description": "Components with the same functionality are identified consistently.",
        "keywords": ["consistent", "label", "icon", "button name", "identification"],
        "common_failures": ["same function has different labels on different pages (e.g., 'Search' vs 'Find')"],
        "axe_rules": [],
        "aria_patterns": [],
        "fix_hint": "Use the same label/name for the same functional component across all pages.",
    },
    "3.2.6": {
        "title": "Consistent Help",
        "level": "A",
        "principle": "Understandable",
        "url": "https://www.w3.org/TR/WCAG22/#consistent-help",
        "description": "Help mechanisms appear in a consistent location relative to other content.",
        "keywords": ["help", "support", "contact", "assistance", "consistent"],
        "common_failures": ["help link appears in different locations across pages"],
        "axe_rules": [],
        "aria_patterns": [],
        "fix_hint": "Place help/contact links in the same location (e.g., always in header or footer).",
    },

    # Guideline 3.3 — Input Assistance
    "3.3.1": {
        "title": "Error Identification",
        "level": "A",
        "principle": "Understandable",
        "url": "https://www.w3.org/TR/WCAG22/#error-identification",
        "description": "Input errors are identified and described to the user in text.",
        "keywords": ["error", "validation", "form error", "error message", "required", "invalid",
                     "aria-invalid", "aria-describedby"],
        "common_failures": [
            "error indicated only by red border with no text message",
            "error message not programmatically associated with the input (no aria-describedby)",
            "error message appears in a different part of the page with no reference to the field",
        ],
        "axe_rules": ["aria-input-field-name"],
        "aria_patterns": ["form pattern"],
        "fix_hint": "Show descriptive text error. Set aria-invalid='true' and aria-describedby pointing to error.",
    },
    "3.3.2": {
        "title": "Labels or Instructions",
        "level": "A",
        "principle": "Understandable",
        "url": "https://www.w3.org/TR/WCAG22/#labels-or-instructions",
        "description": "Labels or instructions are provided when content requires user input.",
        "keywords": ["label", "instruction", "placeholder", "required", "format", "input", "hint"],
        "common_failures": [
            "placeholder used as the only label (disappears on focus)",
            "required fields not indicated",
            "format requirements not communicated (e.g., date format mm/dd/yyyy)",
        ],
        "axe_rules": ["label", "label-title-only"],
        "aria_patterns": [],
        "fix_hint": "Use <label> elements. Show format instructions outside the field. Mark required fields.",
    },
    "3.3.3": {
        "title": "Error Suggestion",
        "level": "AA",
        "principle": "Understandable",
        "url": "https://www.w3.org/TR/WCAG22/#error-suggestion",
        "description": "When an input error is detected, suggestions for correction are provided.",
        "keywords": ["error suggestion", "correction", "fix", "did you mean", "format", "example"],
        "common_failures": ["error says 'invalid input' without explaining what is valid"],
        "axe_rules": [],
        "aria_patterns": [],
        "fix_hint": "Provide specific error messages: 'Email must include @ and domain, e.g. user@example.com'",
    },
    "3.3.4": {
        "title": "Error Prevention (Legal, Financial, Data)",
        "level": "AA",
        "principle": "Understandable",
        "url": "https://www.w3.org/TR/WCAG22/#error-prevention-legal-financial-data",
        "description": "For legal, financial, or test data, submissions are reversible, checked, or confirmed.",
        "keywords": ["undo", "confirm", "review", "checkout", "purchase", "delete", "irreversible"],
        "common_failures": ["one-click purchase with no confirmation step", "no undo for permanent delete"],
        "axe_rules": [],
        "aria_patterns": [],
        "fix_hint": "Add confirmation steps for purchases and deletions. Allow cancellation after submission.",
    },
    "3.3.7": {
        "title": "Redundant Entry",
        "level": "A",
        "principle": "Understandable",
        "url": "https://www.w3.org/TR/WCAG22/#redundant-entry",
        "description": "Information previously entered is auto-populated or available for selection.",
        "keywords": ["redundant entry", "autofill", "re-enter", "previously entered", "copy"],
        "common_failures": ["multi-step form requires re-entering same information"],
        "axe_rules": [],
        "aria_patterns": [],
        "fix_hint": "Auto-populate previously entered information in multi-step forms.",
    },
    "3.3.8": {
        "title": "Accessible Authentication (Minimum)",
        "level": "AA",
        "principle": "Understandable",
        "url": "https://www.w3.org/TR/WCAG22/#accessible-authentication-minimum",
        "description": "Authentication does not require cognitive function tests unless alternatives exist.",
        "keywords": ["captcha", "authentication", "cognitive", "login", "remember password", "copy paste"],
        "common_failures": ["CAPTCHA with no audio alternative", "password field that blocks paste"],
        "axe_rules": [],
        "aria_patterns": [],
        "fix_hint": "Allow password paste. Provide audio CAPTCHA alternatives. Support password managers.",
    },

    # ═══════════════════════════════════════════════════════════════════
    # PRINCIPLE 4: ROBUST
    # ═══════════════════════════════════════════════════════════════════

    # Guideline 4.1 — Compatible
    "4.1.1": {
        "title": "Parsing",
        "level": "A",
        "principle": "Robust",
        "url": "https://www.w3.org/TR/WCAG22/#parsing",
        "description": "HTML has complete start and end tags, no duplicate IDs, and proper nesting.",
        "keywords": ["duplicate id", "parsing", "invalid html", "nesting", "unclosed tag", "id unique"],
        "common_failures": [
            "duplicate id attributes on multiple elements",
            "unclosed HTML tags",
            "invalid element nesting (e.g., block inside inline)",
        ],
        "axe_rules": ["duplicate-id", "duplicate-id-active", "duplicate-id-aria"],
        "aria_patterns": [],
        "fix_hint": "Validate HTML with W3C validator. Ensure all IDs are unique across the page.",
    },
    "4.1.2": {
        "title": "Name, Role, Value",
        "level": "A",
        "principle": "Robust",
        "url": "https://www.w3.org/TR/WCAG22/#name-role-value",
        "description": "UI components have accessible names, roles, and states/properties/values.",
        "keywords": ["aria", "role", "name", "value", "state", "aria-expanded", "aria-selected",
                     "aria-checked", "aria-modal", "custom widget", "accessible name", "aria-label",
                     "aria-labelledby", "aria-describedby", "aria-hidden"],
        "common_failures": [
            "custom button (div/span) with no role='button'",
            "interactive element with no accessible name",
            "expanded/collapsed state not communicated with aria-expanded",
            "form input with no associated label",
            "icon button with no aria-label",
            "modal dialog missing aria-modal and aria-labelledby",
        ],
        "axe_rules": ["aria-allowed-attr", "aria-required-attr", "aria-required-children",
                      "aria-required-parent", "aria-roles", "aria-valid-attr", "aria-valid-attr-value",
                      "button-name", "input-button-name", "select-name", "textarea-label"],
        "aria_patterns": ["button pattern", "dialog pattern", "combobox pattern", "menu pattern",
                          "tab pattern", "accordion pattern"],
        "fix_hint": "Add role, aria-label/labelledby, and state attributes to all custom widgets.",
    },
    "4.1.3": {
        "title": "Status Messages",
        "level": "AA",
        "principle": "Robust",
        "url": "https://www.w3.org/TR/WCAG22/#status-messages",
        "description": "Status messages can be determined programmatically without receiving focus.",
        "keywords": ["status message", "aria-live", "role=status", "role=alert", "role=log",
                     "notification", "toast", "success message", "error message", "live region",
                     "aria-atomic", "polite", "assertive"],
        "common_failures": [
            "success message injected into DOM without role=alert or aria-live",
            "error count updated without aria-live region",
            "toast notification not announced to screen readers",
            "form validation errors appear without live region announcement",
        ],
        "axe_rules": ["aria-live-region-valid"],
        "aria_patterns": ["alert pattern", "status pattern", "log pattern"],
        "fix_hint": "Add role='alert' or aria-live='polite'/'assertive' to dynamically injected messages.",
    },
}


# ── ARIA Design Patterns ─────────────────────────────────────────────────────
# Source: https://www.w3.org/WAI/ARIA/apg/patterns/

ARIA_PATTERNS: dict[str, dict] = {
    "dialog": {
        "name": "Dialog (Modal)",
        "url": "https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/",
        "required_role": "dialog",
        "required_attrs": ["aria-labelledby or aria-label", "aria-modal='true'"],
        "keyboard": {
            "Tab": "Move focus to next tabbable element inside dialog",
            "Shift+Tab": "Move focus to previous tabbable element inside dialog",
            "Escape": "Close the dialog and return focus to the trigger element",
        },
        "focus_management": (
            "When dialog opens, focus must move to the first focusable element inside it. "
            "Focus must be trapped inside the dialog. When dialog closes, focus returns to the trigger."
        ),
        "anti_patterns": [
            "Focus not moved to dialog on open",
            "aria-modal='true' missing",
            "No aria-labelledby or aria-label on dialog",
            "Escape key does not close dialog",
            "Focus escapes dialog when pressing Tab at last element",
        ],
        "wcag": ["2.1.2", "4.1.2"],
    },
    "button": {
        "name": "Button",
        "url": "https://www.w3.org/WAI/ARIA/apg/patterns/button/",
        "required_role": "button (implicit on <button> element)",
        "required_attrs": ["accessible name via text content, aria-label, or aria-labelledby"],
        "keyboard": {
            "Enter": "Activate the button",
            "Space": "Activate the button",
        },
        "anti_patterns": [
            "div or span used as button without role='button'",
            "Button with no accessible name (icon-only with no aria-label)",
            "onclick only — no keydown handler for Enter/Space on custom buttons",
        ],
        "wcag": ["2.1.1", "4.1.2"],
    },
    "accordion": {
        "name": "Accordion",
        "url": "https://www.w3.org/WAI/ARIA/apg/patterns/accordion/",
        "required_role": "Each header is a <button> with aria-expanded and aria-controls",
        "required_attrs": ["aria-expanded", "aria-controls", "id on panel"],
        "keyboard": {
            "Enter / Space": "Toggle the accordion panel",
            "Tab": "Move to next focusable element",
        },
        "anti_patterns": [
            "Accordion header is not a button",
            "aria-expanded not updated on toggle",
            "aria-controls not pointing to the correct panel",
        ],
        "wcag": ["2.1.1", "4.1.2"],
    },
    "tabs": {
        "name": "Tabs",
        "url": "https://www.w3.org/WAI/ARIA/apg/patterns/tabs/",
        "required_role": "role='tablist' on container, role='tab' on tabs, role='tabpanel' on panels",
        "required_attrs": ["aria-selected", "aria-controls", "aria-labelledby"],
        "keyboard": {
            "Tab": "Move focus to active tab, then to tabpanel",
            "Arrow Left/Right": "Move focus between tabs",
            "Enter/Space": "Activate tab (manual activation pattern)",
        },
        "anti_patterns": [
            "Tab activation requires click only",
            "aria-selected not updated when tab is activated",
            "tabpanel not labelled by corresponding tab",
        ],
        "wcag": ["2.1.1", "4.1.2"],
    },
    "combobox": {
        "name": "Combobox",
        "url": "https://www.w3.org/WAI/ARIA/apg/patterns/combobox/",
        "required_role": "role='combobox' on input, role='listbox' on dropdown, role='option' on items",
        "required_attrs": ["aria-expanded", "aria-controls", "aria-autocomplete", "aria-activedescendant"],
        "keyboard": {
            "Down Arrow": "Open listbox / move to next option",
            "Up Arrow": "Move to previous option",
            "Enter": "Select the focused option",
            "Escape": "Close the listbox",
        },
        "anti_patterns": [
            "Custom dropdown with no ARIA roles",
            "aria-expanded not updated",
            "Selected option not communicated",
        ],
        "wcag": ["2.1.1", "4.1.2"],
    },
    "menu": {
        "name": "Menu and Menubar",
        "url": "https://www.w3.org/WAI/ARIA/apg/patterns/menu/",
        "required_role": "role='menu' or role='menubar', role='menuitem' on items",
        "required_attrs": ["aria-haspopup", "aria-expanded on trigger"],
        "keyboard": {
            "Enter/Space": "Open submenu or activate item",
            "Arrow Down/Up": "Navigate menu items",
            "Arrow Right/Left": "Open/close submenus",
            "Escape": "Close menu and return focus to trigger",
            "Tab": "Close menu",
        },
        "anti_patterns": [
            "Navigation using ul/li without menu roles when acting as application menu",
            "Submenus opened on hover only",
        ],
        "wcag": ["2.1.1", "4.1.2"],
    },
    "alert": {
        "name": "Alert",
        "url": "https://www.w3.org/WAI/ARIA/apg/patterns/alert/",
        "required_role": "role='alert' or aria-live='assertive'",
        "required_attrs": [],
        "keyboard": {},
        "focus_management": "Alert is announced automatically. Focus is NOT moved to it.",
        "anti_patterns": [
            "Success/error message injected into DOM with no aria-live or role=alert",
            "Alert element hidden initially and shown later (must be in DOM with role=alert from start)",
        ],
        "wcag": ["4.1.3"],
    },
    "tooltip": {
        "name": "Tooltip",
        "url": "https://www.w3.org/WAI/ARIA/apg/patterns/tooltip/",
        "required_role": "role='tooltip' on tooltip element",
        "required_attrs": ["aria-describedby on the trigger pointing to tooltip id"],
        "keyboard": {
            "Escape": "Dismiss the tooltip",
        },
        "anti_patterns": [
            "Tooltip only visible on hover (not on keyboard focus)",
            "Tooltip disappears when mouse moves to it",
            "No role=tooltip on element",
        ],
        "wcag": ["1.4.13", "4.1.2"],
    },
}
